apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastercode-deploy
  namespace: sourcecode
spec:
  selector:
    matchLabels:
      app: code
      env: prod
      type: mastercode
  replicas: 1
  template:
    metadata:
      labels:
        app: code
        env: prod
        type: mastercode
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: Exists
      containers:
      - name: mastercode-pod
        image: gcr.io/source-code-oj/mastercode:0.0.10
        ports:
        - containerPort: 80
        volumeMounts:
        - name: mastercode-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          readOnly: true
        - name: mastercode-config-volume
          mountPath: /var/www/html/.env
          subPath: .env
          readOnly: true
        livenessProbe:
          httpGet:
              path: /api/v1/ping
              port: 80
          initialDelaySeconds: 5
          failureThreshold: 2
          periodSeconds: 5
        resources:
          requests:
            cpu: 200m
            memory: 256M
          limits:
            cpu: 250m
            memory: 300M
      volumes:
      - name: mastercode-config-volume
        configMap:
          name:  mastercode-configs
---
apiVersion: v1
kind: Service
metadata:
  name: mastercode-service
  namespace: sourcecode
  labels:
    app: code
    env: prod
    type: mastercode
spec:
  selector:
    app: code
    env: prod
    type: mastercode
  type: NodePort
  ports:
  - port: 80
    nodePort: 32105
    name: mastercode-port
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mastercode-ingress
  namespace: sourcecode
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: ssl-key-api.beta.sustcseoj.com
    hosts: 
    - api.beta.sustcseoj.com
  rules:
  - host: api.beta.sustcseoj.com
    http:
      paths:
      - path: /
        backend:
          serviceName: mastercode-service
          servicePort: 80