apiVersion: v1
kind: ConfigMap
metadata:
  name: judgemod-config
  namespace: sourcecode
  labels:
    app: code
    env: prod
    type: judgemod
data:
  config.ini: |
    [basic]
    name = Source Code Online Judge
    [database]
    db_name = source_code_v2
    db_host = mysql-service.sourcecode
    db_username = 
    db_password = 

    [judgeenv]
    max_sub = 1
    sub_data_path = /home/judge/sub_data

    [taskQueue]
    host = rmq-service.sourcecode
    port = 5672
    username = 
    password = 
    sub_queue_name = submissions
    connection_retry_delay = 10
    max_connection_retry = 15
    not_queue_name = notifications
    routing_key = notifications
    durable = True
    ttl = 600000

    [fileServerSettings]
    service_name = s3
    cache_path = /home/judge/judge_cache
    storage_access_key_id = 
    storage_secret_access_key = 
    storage_default_region = 
    storage_bucket = 
    storage_url = 
    storage_endpoint = 

    account_credential=/home/judge/gcs_service_account.json

    [binLanguage]
    lang_ids = 0,1,2,3,5,6,7,8

    [vmLanguage]
    lang_ids = 4

    [binCompilerCmds]
    # corresponding compiler command
    command = gcc,g++,python2,python3,g++,g++,go,node

    [vmCompilerCmds]
    compiler = javac10
    vm = java10

    [log]
    log_file_path = /var/log/judgemod
    file_log_level = INFO
    console_log_level = DEBUG