apiVersion: batch/v1
kind: Job
metadata:
  name: letsencrypt-job
  namespace: sourcecode
  labels:
    app: code
    env: prod
    type: ssl
spec:
  template:
    metadata:
      name: letsencrypt
      labels:
        app: code
        env: prod
        type: ssl
    spec:
      serviceAccount: ssl-manager
      containers:
      - name: letsencrypt-job-pod
        image: registry.hub.docker.com/rafikfarhad/kubernetes-nginx-letsencrypt:0.0.13
        # command:
        # - sleep
        # - "3600"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: DOMAINS
          # value: beta.sustcseoj.com,api.beta.sustcseoj.com,judge.beta.sustcseoj.com,live.beta.sustcseoj.com,rmq.beta.sustcseoj.com
          value: rmq.beta.sustcseoj.com
        - name: SECRETS
          # value: ssl-key-beta.sustcseoj.com,ssl-key-api.beta.sustcseoj.com,ssl-key-judge.beta.sustcseoj.com,ssl-key-live.beta.sustcseoj.com,ssl-key-rmq.beta.sustcseoj.com
          value: ssl-key-rmq.beta.sustcseoj.com
        - name: EMAIL
          value: rafikfarhad@gmail.com
        - name: NAMESPACE
          value: sourcecode
        - name: CLUSTER_ADDRESS
          value: 34.70.78.147
        - name: DO_NOT_UPDATE_WINDOW
          value: "14"
      restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: letsencrypt-service
  namespace: sourcecode
spec:
  selector:
    app: code
    env: prod
    type: ssl
  type: NodePort
  ports:
  - port: 80
    nodePort: 32109
    name: letsencrypt-port
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: letsencrypt-ingress
  namespace: sourcecode
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: beta.sustcseoj.com
    http:
      paths:
      - path: /.well-known
        backend:
          serviceName: letsencrypt-service
          servicePort: 80
  - host: api.beta.sustcseoj.com
    http:
      paths:
      - path: /.well-known
        backend:
          serviceName: letsencrypt-service
          servicePort: 80
  - host: judge.beta.sustcseoj.com
    http:
      paths:
      - path: /.well-known
        backend:
          serviceName: letsencrypt-service
          servicePort: 80
  - host: live.beta.sustcseoj.com
    http:
      paths:
      - path: /.well-known
        backend:
          serviceName: letsencrypt-service
          servicePort: 80
  - host: rmq.beta.sustcseoj.com
    http:
      paths:
      - path: /.well-known
        backend:
          serviceName: letsencrypt-service
          servicePort: 80