apiVersion: apps/v1
kind: Deployment
metadata:
  name: subcode-queue-deploy
  namespace: sourcecode
spec:
  selector:
    matchLabels:
      app: code
      env: prod
      type: subcode-queue
  replicas: 1
  template:
    metadata:
      labels:
        app: code
        env: prod
        type: subcode-queue
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: Exists
      containers:
      - name: subcode-queue-pod
        image: gcr.io/source-code-oj/subcode-queue:0.0.15
        volumeMounts:
        - name: subcode-config-volume
          mountPath: /var/www/html/.env
          subPath: .env
          readOnly: true
        - name: subcode-config-volume
          mountPath: /var/www/html/config/gcs/gcs.json
          subPath: gcs.json
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 128M
          limits:
            cpu: 150m
            memory: 256M
      volumes:
      - name: subcode-config-volume
        configMap:
          name:  subcode-configs