apiVersion: apps/v1
kind: Deployment
metadata:
  name: subcode-deploy
  namespace: sourcecode
spec:
  selector:
    matchLabels:
      app: code
      env: prod
      type: subcode
  replicas: 1
  template:
    metadata:
      labels:
        app: code
        env: prod
        type: subcode
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: Exists
      containers:
      - name: subcode-pod
        image: gcr.io/source-code-oj/subcode:0.0.19
        # imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: subcode-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          readOnly: true
        - name: subcode-config-volume
          mountPath: /var/www/html/.env
          subPath: .env
          readOnly: true
        - name: subcode-config-volume
          mountPath: /var/www/html/config/gcs/gcs.json
          subPath: gcs.json
          readOnly: true
        livenessProbe:
          httpGet:
              path: /
              port: 80
          initialDelaySeconds: 5
          failureThreshold: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
              path: /
              port: 80
          initialDelaySeconds: 5
          failureThreshold: 2
          periodSeconds: 5
        resources:
          limits:
            cpu: 150m
            memory: 256M
      volumes:
      - name: subcode-config-volume
        configMap:
          name:  subcode-configs
---
apiVersion: v1
kind: Service
metadata:
  name: subcode-service
  namespace: sourcecode
  labels:
    app: code
    env: prod
    type: subcode
spec:
  selector:
    app: code
    env: prod
    type: subcode
  type: NodePort
  ports:
  - port: 80
    nodePort: 32107
    name: subcode-port
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: subcode-ingress
  namespace: sourcecode
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: ssl-key-judge.beta.sustcseoj.com
  rules:
  - host: judge.beta.sustcseoj.com
    http:
      paths:
      - path: /
        backend:
          serviceName: subcode-service
          servicePort: 80
