apiVersion: apps/v1
kind: Deployment
metadata:
  name: docode-deploy
  namespace: sourcecode
spec:
  selector:
    matchLabels:
      app: code
      env: prod
      type: docode
  replicas: 1
  template:
    metadata:
      labels:
        app: code
        env: prod
        type: docode
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: Exists
      containers:
      - name: docode-pod
        image: gcr.io/source-code-oj/docode:0.0.4
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 190m
            memory: 1024M
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: docode-service
  namespace: sourcecode
  labels:
    app: code
    env: prod
    type: docode
spec:
  selector:
    app: code
    env: prod
    type: docode
  type: NodePort
  ports:
  - port: 3000
    nodePort: 32108
    name: docode-port
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: docode-ingress
  namespace: sourcecode
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: ssl-key-beta.sustcseoj.com
    hosts:
      - beta.sustcseoj.com
  rules:
  - host: beta.sustcseoj.com
    http:
      paths:
      - path: /
        backend:
          serviceName: docode-service
          servicePort: 3000