apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim-1
  namespace: sourcecode
  labels:
    app: code
    env: prod
    type: pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi